### Importando librerías

In [2]:
import numpy as np

In [ ]:
arr = np.random.randint(1,20,10)

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[19,  9, 15, 15, 16],
       [18, 19, 16, 12, 14]])

In [ ]:
arr

array([19,  9, 15, 15, 16, 18, 19, 16, 12, 14])

### Max

In [ ]:
arr.max()

19

In [ ]:
matriz

array([[19,  9, 15, 15, 16],
       [18, 19, 16, 12, 14]])

In [ ]:
matriz.max(0)

array([19, 19, 16, 15, 16])

### Argmax

In [ ]:
arr.argmax()

0

In [ ]:
matriz.argmax(0)

array([0, 1, 1, 0, 0])

### Min

In [ ]:
arr.min()

9

In [ ]:
matriz.min(0)

array([18,  9, 15, 12, 14])

### Argmin

In [ ]:
arr.argmin()

1

In [ ]:
matriz.argmin(1)

array([1, 3])

### Ptp

In [ ]:
arr

array([19,  9, 15, 15, 16, 18, 19, 16, 12, 14])

In [ ]:
arr.ptp()

10

In [ ]:
matriz.ptp(0)

array([ 1, 10,  1,  3,  2])

### Sort

In [ ]:
arr.sort()
arr

array([ 9, 12, 14, 15, 15, 16, 16, 18, 19, 19])

### Percentile

In [ ]:
np.percentile(arr,50)

15.5

### Median

In [ ]:
np.median(arr)

15.5

In [ ]:
np.median(matriz,1)

array([14., 18.])

### Standard Deviation (std)

In [ ]:
np.std(arr) ** 2

8.81

### Variance (Var)

In [ ]:
np.var(arr)

8.81

### Mean

In [ ]:
np.mean(arr)

15.3

### Concatenate

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [4]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [5]:
a.ndim
b.ndim

1

In [ ]:
b = np.expand_dims(b,axis=0)

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b

array([[5, 6]])

In [ ]:
np.concatenate((a,b),axis=1)

ValueError: ignored

In [ ]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### Transpuesta

In [ ]:
b.T

array([[5],
       [6]])