### Importar librerías

In [16]:
import numpy as np

In [17]:
lista = [1,2]
lista

[1, 2]

In [18]:
lista * 2

[1, 2, 1, 2]

In [19]:
arr = np.arange(0,10)
arr2 = arr.copy()

### Operaciones (aritmética simple al array)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
1 / arr 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [24]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Operaciones entre arrays

In [25]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
arr - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [28]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [29]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [31]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [33]:
np.matmul(matriz,matriz2.T) #Producto punto

array([[ 30,  80],
       [ 80, 255]])

In [34]:
matriz @ matriz2.T #Otra forma de realizar producto punto

array([[ 30,  80],
       [ 80, 255]])