### Importar librerías

In [1]:
import numpy as np 

In [3]:
arr = np.random.randint(1,10,(3,2))

### Shape

In [ ]:
arr.shape

(3, 2)

In [4]:
arr

array([[9, 5],
       [2, 7],
       [1, 1]])

### Reshape

In [ ]:
arr.reshape(1,6)

array([[9, 6, 8, 9, 4, 2]])

In [ ]:
arr.reshape(2,3)

array([[9, 6, 8],
       [9, 4, 2]])

In [ ]:
np.reshape(arr,(1,6))

array([[9, 6, 8, 9, 4, 2]])

In [ ]:
arr

array([[9, 6],
       [8, 9],
       [4, 2]])

In [ ]:
np.reshape(arr,(2,3),'C')

array([[9, 6, 8],
       [9, 4, 2]])

In [ ]:
np.reshape(arr,(2,3),'F')

array([[9, 4, 9],
       [8, 6, 2]])

In [ ]:
np.reshape(arr,(2,3),'A')

array([[9, 6, 8],
       [9, 4, 2]])